files:
  - source: /NodeControllerRenewal/Properties/Localize.resx
    translation: /NodeControllerRenewal/Properties/Localize.%two_letters_code%.resx
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        "zh-CN": "zh-CN"
        "zh-TW": "zh-TW"
        "en-GB": "en-GB"
